default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todo_rails
  username: ghost
  password: Dkflbr100499
  host: localhost
  port: 5432

test:
  <<: *default
  database: todo_app_test

production:
  <<: *default
  database: <%= ENV["TODO_APP_DBNAME"] %>
  username: <%= ENV["TODO_APP_USERNAME"] %>
  password: <%= ENV["TODO_APP_DATABASE_PASSWORD"] %>
